import Header from "../Header/Header";
import { Button, useTheme, useMediaQuery, Accordion, AccordionSummary, AccordionDetails, Typography } from "@mui/material";
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux";

function Pantry() {
    const dispatch = useDispatch();
    const userPreferences = useSelector(store => store.userPreferencesReducer);
    const userHouseholdItems = useSelector(store => store.userHouseholdItemsReducer);
    const [preferencesToDisplay, setPreferencesToDisplay] = useState([]);
    const [householdItemsToDisplay, setHouseholdItemsToDisplay] = useState([]);
    const [expandedSection, setExpandedSection] = useState(null);

    const pantryEssentials = [
        "Butter",
        "Egg",
        "Garlic",
        "Milk",
        "Onion",
        "Sugar",
        "Flour",
        "Olive oil",
        "Garlic powder",
        "White rice",
        "Cinnamon",
        "Ketchup",
        "Soy sauce",
        "Mayonnaise",
        "Vegetable oil",
        "Bread",
        "Baking powder",
        "Brown sugar",
        "Oregano",
        "Potato",
        "Honey",
        "Paprika",
        "Baking soda",
        "Vanilla",
        "Spaghetti",
        "Peanut butter",
        "Chili powder",
        "Cumin",
        "Mustard",
        "Chicken breast",
        "Cheddar",
        "Onion powder",
        "Carrot",
        "Tomato",
        "Tomato",
        "Basil",
        "Parsley",
        "Parmesean",
        "Italian seasoning",
        "Thyme",
        "Bell pepper",
    ];

    const vegetablesAndGreens = [
        "Scallion",
        "Red onion",
        "Celery",
        "Jalapeño",
        "Avocado",
        "Zucchini",
        "Shallot",
        "Cherry tomato",
        "Cucumber",
        "Spinach",
        "Corn",
        "Chile pepper",
        "Sweet potato",
        "Broccoli",
        "Baby greens",
        "Pumpkin",
        "Cauliflower",
        "Asparagus",
        "Cabbage",
        "Arugula",
        "Leek",
        "Kale",
        "Eggplant",
        "Lettuce",
        "Butternut squash",
        "Romaine",
        "Beetroot",
        "Brussels sprout",
        "Fennel",
        "Sun-dried tomato",
        "Radish",
        "Red cabbage",
        "Artichoke",
        "Summer squash",
        "Mixed greens",
        "Parsnip",
        "Baby carrot",
        "Mixed vegetable",
        "Poblano pepper",
        "Sweet pepper",
        "Green tomato",
        "Serrano pepper",
        "Watercress",
        "Iceberg lettuce",
        "Mashed potatoes",
        "Horseradish",
        "Chard",
        "Hash browns",
        "Pimento",
        "Napa cabbage",
        "Butter lettuce",
        "Spaghetti squash",
        "Coleslaw",
        "Celeriac",
        "Turnip",
        "Bok choy",
        "Okra",
        "Acorn squash",
        "Corn cob",
        "Raddichio",
        "Water chestnut",
        "Pearl onion",
        "Pepperoncini",
        "Tenderstem broccoli",
        "Leaf lettuce",
        "Cavolo nero",
        "Baby boy choy",
        "Endive",
        "Plantain",
        "Jicama",
        "Collard greens",
        "Habañero pepper",
        "Corn husk",
        "Fried onion",
        "Daikon",
        "Baby corn",
        "Broccoli rabe",
        "Belgian endive",
        "Rutabaga",
        "Kohlrabi",
        "Boston lettuce",
        "Fresno chile",
        "Microgreens",
        "Yam",
        "Ancho chile peppers",
        "Delicata squash",
        "Anaheim pepper",
        "Cress",
        "Frisée",
        "Broccoli slaw",
        "Potato flakes",
        "Golden beet",
        "Gem lettuce",
    ];

    const mushrooms = [
        "Button mushroom",
        "Shiitake mushroom",
        "Portobello mushroom",
        "Wild mushroom",
        "Porcini mushroom",
        "Oyster mushroom",
        "Cremini mushroom",
        "Mixed mushrooms",
        "Chestnut mushroom",
        "Chanterelle mushroom",
        "Enoki mushroom",
        "Morel mushroom",
        "Black fungus mushroom",
        "Black truffle mushroom",
        "Field mushroom",
        "King oyster mushroom",
        "Straw mushroom",
        "Wood ear mushroom",
        "White truffle mushroom",
        "Shimeji mushroom",
        "Dried chinese mushroom",
        "Maitake mushroom",
        "Trumpet mushroom",
        "Lion's mane mushroom",
        "White fungus mushroom",
        "Pioppini mushroom",
        "Snow fungus mushroom",
        "White beech mushroom",
        "Huitlacoche mushroom",
        "Matsutake mushroom",
        "Nameko mushroom",
        "Boletus mushroom",
        "Djon djon mushroom",
        "Mixed Asian mushrooms",
        "Puffball mushroom",
        "Honey fungus mushroom",
        "Lobster mushroom",
        "Saffron milk cap mushroom",
        "Caesar's mushroom",
        "Candy cap mushroom",
    ];

    const fruits = [
        "Apple",
        "Banana",
        "Orange",
        "Strawberry",
        "Blueberry",
        "Raspberry",
        "Blackberry",
        "Cherry",
        "Grape",
        "Watermelon",
        "Cantaloupe",
        "Honeydew",
        "Pineapple",
        "Mango",
        "Peach",
        "Nectarine",
        "Plum",
        "Apricot",
        "Kiwi",
        "Gold kiwi",
        "Pear",
        "Pomegranate",
        "Papaya",
        "Grapefruit",
        "Lemon",
        "Lime",
        "Coconut",
        "Cranberry",
        "Gooseberry",
        "Lychee",
        "Passionfruit",
        "Guava",
        "Dragonfruit",
        "Starfruit",
        "Jackfruit",
        "Durian",
        "Tangerine",
        "Clementine",
        "Mandarin",
        "Satsuma",
        "Fig",
        "Date",
        "Prune",
        "Mulberry",
        "Elderberry",
        "Currant",
        "Persimmon",
        "Rhubarb",
        "Quince",
        "Kumquat",
        "Tamarind",
        "Avocado",
        "Olive",
        "Breadfruit",
        "Rambutan",
        "Longan",
        "Jujube",
        "Salak",
        "Cherimoya",
        "Feijoa",
        "Huckleberry",
        "Marionberry",
        "Boysenberry",
        "Loganberry",
        "Cloudberry",
        "Ackee",
        "Soursop",
        "Custard Apple",
        "Horned Melon",
        "Miracle Fruit",
        "Medlar",
        "Buddha's Hand",
        "Calamansi",
        "Pomelo",
        "Santol",
        "Sapodilla",
        "Malay Apple",
        "Rose Apple",
        "Pineberry",
        "Barberry",
        "Sea Buckthorn",
        "Maqui Berry",
        "Camu Camu",
        "Acerola",
        "Jabuticaba",
        "Surinam Cherry",
        "Caimito",
        "Sweetsop",
        "Atemoya",
        "Chokeberry",
        "Bilberry",
        "Serviceberry",
        "Mayhaw",
        "Hog Plum",
        "Indian Gooseberry",
        "Bael",
        "Bignay",
        "Bacaba",
        "Buriti",
        "Dried fruit",
        "Frozen fruit",
        "Canned fruit",
        "Dried strawberry",
        "Dried mango",
        "Dried cranberry",
        "Dried apple",
        "Dried apricot",
        "Dried fig",
        "Dried cherry",
        "Dried blueberry",
        "Dried papaya",
        "Dried pineapple",
        "Dried peach",
        "Dried plum",
        "Dried banana",
        "Dried raspberry",
        "Dried blackberry",
        "Dried grape",
        "Dried coconut",
        "Raisin",
    ];

    const nutsAndSeeds = [
        "Almond",
        "Peanut",
        "Walnut",
        "Cashew",
        "Pistachio",
        "Hazelnut",
        "Pecan",
        "Macadamia",
        "Brazil Nut",
        "Chestnut",
        "Pine Nut",
        "Sunflower Seed",
        "Pumpkin Seed",
        "Sesame Seed",
        "Chia Seed",
        "Flaxseed",
        "Hemp Seed",
        "Poppy Seed",
        "Safflower Seed",
        "Mustard Seed",
        "Coriander Seed",
        "Caraway Seed",
        "Fennel Seed",
        "Cumin Seed",
        "Nigella Seed",
        "Fenugreek Seed",
        "Celery Seed",
        "Cardamom Seed",
        "Basil Seed",
        "Watermelon Seed",
        "Cantaloupe Seed",
        "Grape Seed",
        "Cucumber Seed",
        "Quinoa",
        "Amaranth",
        "Teff",
        "Millet",
        "Buckwheat",
        "Barley",
        "Sorghum",
        "Oat",
        "Wheat Berry",
        "Spelt",
        "Kamut",
        "Einkorn",
        "Farro",
        "Rye Berry",
        "Freekeh",
        "Bulgar",
        "Chufa",
        "Lotus Seed",
        "Gingko Nut",
        "Sacha Inchi",
        "Acorn",
        "Breadnut",
        "Jackfruit Seed",
    ];

    const cheeses = [
        "Cheddar",
        "Mozzarella",
        "Parmesan",
        "Brie",
        "Swiss",
        "Gouda",
        "Feta",
        "Provolone",
        "Monterey Jack",
        "Colby",
        "Blue Cheese",
        "Camembert",
        "Ricotta",
        "Cream Cheese",
        "Goat Cheese",
        "Havarti",
        "Gruyère",
        "Asiago",
        "Manchego",
        "Pecorino Romano",
        "Emmental",
        "Mascarpone",
        "Roquefort",
        "Gorgonzola",
        "Fontina",
        "Queso Blanco",
        "Cottage Cheese",
        "Paneer",
        "Halloumi",
        "Burrata",
        "Stilton",
        "Limburger",
        "Muenster",
        "Neufchâtel",
        "Cotija",
        "Edam",
        "Taleggio",
        "Jarlsberg",
        "Appenzeller",
        "Reblochon",
        "Tête de Moine",
        "Mahon",
        "Vacherin",
        "Epoisses",
        "Grana Padano",
        "Queso Fresco",
        "Oaxaca",
        "Raclette",
        "Beaufort",
        "Port Salut",
        "Boursin",
        "Ricotta Salata",
        "Fromage Blanc",
        "Wensleydale",
        "Red Leicester",
        "Double Gloucester",
        "Caerphilly",
        "Lancashire",
        "Cheshire",
        "Shropshire Blue",
        "Dorset Blue Vinny",
        "Yarg",
        "Mimolette",
        "Pont-l'Évêque",
        "Brillat-Savarin",
        "Chaource",
        "Delice de Bourgogne",
        "Cantal",
        "Fourme d'Ambert",
        "Saint-Nectaire",
        "Morbier",
        "Abondance",
        "Tomme de Savoie",
        "Salers",
        "Crottin de Chavignol",
        "Valençay",
        "Banon",
        "Picodon",
        "Chabichou",
        "Leerdammer",
        "Parrano",
        "Leyden",
        "Aged Gouda",
        "Gjetost",
        "Danish Blue",
        "Saga Blue",
        "Havarti",
        "Samso",
        "Cambozola",
        "Brick Cheese",
        "Colby-Jack",
        "Pepper Jack",
        "Queso de Bola",
        "Queso Chihuahua",
        "Tetilla",
        "Idiazabal",
        "Roncal",
        "Mahon Menorca",
        "Nabulsi",
        "Kashkaval",
        "Akawi",
    ];

    const meatAndDairySubstitutes = [
        "Tofu",
        "Tempeh",
        "Seitan",
        "Jackfruit",
        "Beyond Meat",
        "Impossible Burger",
        "Textured Vegetable Protein (TVP)",
        "Lentils",
        "Chickpeas",
        "Black Beans",
        "Kidney Beans",
        "Nutritional Yeast",
        "Coconut Milk",
        "Almond Milk",
        "Soy Milk",
        "Oat Milk",
        "Rice Milk",
        "Cashew Milk",
        "Hemp Milk",
        "Pea Milk",
        "Coconut Yogurt",
        "Almond Yogurt",
        "Soy Yogurt",
        "Oat Yogurt",
        "Rice Yogurt",
        "Cashew Yogurt",
        "Hemp Yogurt",
        "Coconut Ice Cream",
        "Almond Ice Cream",
        "Soy Ice Cream",
        "Oat Ice Cream",
        "Rice Ice Cream",
        "Cashew Ice Cream",
        "Hemp Ice Cream",
        "Mushrooms",
        "Cauliflower",
        "Eggplant",
        "Zucchini",
        "Carrot Bacon",
        "Coconut Bacon",
        "Rice Paper Bacon",
        "Aquafaba",
        "Cashew Cheese",
        "Almond Cheese",
        "Soy Cheese",
        "Hemp Cheese",
        "Pea Protein",
        "Quinoa",
        "Buckwheat",
    ];

    [
        "Beef",
        "Ground Beef",
        "Beef Steak",
        "Beef Roast",
        "Beef Ribs",
        "Beef Brisket",
        "Beef Tenderloin",
        "Corned Beef",
        "Beef Jerky",
        "Veal",
        "Pork",
        "Ground Pork",
        "Pork Chops",
        "Pork Roast",
        "Pork Ribs",
        "Pork Belly",
        "Ham",
        "Bacon",
        "Prosciutto",
        "Pancetta",
        "Salami",
        "Pepperoni",
        "Sausage",
        "Chicken",
        "Chicken Breast",
        "Chicken Thigh",
        "Chicken Wings",
        "Chicken Drumsticks",
        "Chicken Liver",
        "Chicken Sausage",
        "Turkey",
        "Ground Turkey",
        "Turkey Breast",
        "Turkey Legs",
        "Turkey Wings",
        "Turkey Sausage",
        "Duck",
        "Duck Breast",
        "Duck Legs",
        "Duck Liver",
        "Duck Confit",
        "Goose",
        "Goose Breast",
        "Goose Legs",
        "Goose Liver",
        "Rabbit",
        "Rabbit Loin",
        "Rabbit Legs",
        "Venison",
        "Venison Steak",
        "Venison Sausage",
        "Bison",
        "Bison Steak",
        "Bison Burger",
        "Lamb",
        "Lamb Chops",
        "Lamb Roast",
        "Lamb Shank",
        "Ground Lamb",
        "Lamb Sausage",
        "Mutton",
        "Goat",
        "Ground Goat",
        "Goat Stew",
        "Quail",
        "Pheasant",
        "Partridge",
        "Guinea Fowl",
        "Ostrich",
        "Ostrich Steak",
        "Emu",
        "Buffalo",
        "Buffalo Steak",
        "Buffalo Burger",
        "Wild Boar",
        "Boar Sausage",
        "Kangaroo",
        "Elk",
        "Elk Steak",
        "Elk Burger",
        "Camel",
        "Yak",
        "Alligator",
        "Alligator Sausage",
        "Crocodile",
        "Snake",
        "Frog Legs",
        "Turtle",
        "Seal",
        "Reindeer",
        "Moose",
        "Squirrel",
        "Pigeon",
        "Capybara",
        "Bratwurst",
        "Hot Dog",
        "Bologna",
        "Liverwurst",
        "Chorizo",
        "Andouille",
        "Kielbasa",
        "Polish Sausage",
        "Italian Sausage",
        "Chicken liver",
        "Duck liver",
        "Cow liver",
    ];

    const seafood = [
        "Salmon",
        "Smoked salmon",
        "Tuna",
        "Cod",
        "Haddock",
        "Trout",
        "Halibut",
        "Mackerel",
        "Sardines",
        "Anchovies",
        "Snapper",
        "Sea Bass",
        "Grouper",
        "Swordfish",
        "Tilapia",
        "Flounder",
        "Catfish",
        "Pollock",
        "Barramundi",
        "John Dory",
        "Monkfish",
        "Hake",
        "Whiting",
        "Sole",
        "Skate",
        "Marlin",
        "Bluefish",
        "Pompano",
        "Mahi Mahi",
        "Wahoo",
        "Lingcod",
        "Rockfish",
        "Amberjack",
        "Sheepshead",
        "Tilefish",
        "Whitefish",
        "Opah",
        "Escolar",
        "Butterfish",
        "Flying Fish",
        "Scallops",
        "Shrimp",
        "Prawns",
        "Lobster",
        "Crab",
        "King Crab",
        "Snow Crab",
        "Dungeness Crab",
        "Blue Crab",
        "Stone Crab",
        "Crawfish",
        "Oysters",
        "Clams",
        "Mussels",
        "Octopus",
        "Squid",
        "Calamari",
        "Cuttlefish",
        "Abalone",
        "Conch",
        "Sea Urchin",
        "Razor Clams",
        "Cockles",
        "Geoduck",
        "Periwinkles",
        "Barnacles",
        "Sea Cucumber",
        "Sea Snails",
        "Seaweed",
        "Kelp",
        "Wakame",
        "Nori",
        "Dulse",
        "Agar",
        "Sea Grapes",
        "Eel",
        "Unagi",
        "Anago",
        "Fish Roe",
        "Caviar",
        "Flying Fish Roe",
        "Salmon Roe",
        "Tobiko",
        "Ikura",
        "Lumpfish Roe",
        "Whitebait",
        "Smelt",
        "Capelin",
        "Sprat",
        "Herring",
        "Kippers",
        "Arctic Char",
        "Steelhead",
        "Yellowtail",
        "Bonito",
        "Albacore",
        "Bigeye Tuna",
        "Yellowfin Tuna",
        "Bluefin Tuna",
        "Mahi Mahi",
        "Triggerfish",
        "Surimi",
    ];

    const herbsAndSpices = [
        "Basil",
        "Oregano",
        "Thyme",
        "Rosemary",
        "Parsley",
        "Cilantro",
        "Dill",
        "Mint",
        "Sage",
        "Chives",
        "Tarragon",
        "Marjoram",
        "Bay Leaves",
        "Lemongrass",
        "Savory",
        "Fennel",
        "Lavender",
        "Sorrel",
        "Chervil",
        "Epazote",
        "Curry Leaves",
        "Paprika",
        "Turmeric",
        "Cumin",
        "Coriander",
        "Cardamom",
        "Cloves",
        "Nutmeg",
        "Cinnamon",
        "Ginger",
        "Garlic Powder",
        "Onion Powder",
        "Mustard Seeds",
        "Fenugreek",
        "Caraway",
        "Anise",
        "Star Anise",
        "Sumac",
        "Saffron",
        "Black Pepper",
        "White Pepper",
        "Pink Peppercorn",
        "Green Peppercorn",
        "Allspice",
        "Juniper Berries",
        "Cayenne Pepper",
        "Chili Powder",
        "Crushed Red Pepper",
        "Chipotle",
        "Aleppo Pepper",
        "Habanero Powder",
        "Smoked Paprika",
        "Hungarian Paprika",
        "Spanish Paprika",
        "Chinese Five Spice",
        "Za'atar",
        "Ras el Hanout",
        "Garam Masala",
        "Harissa",
        "Berbere",
        "Baharat",
        "Advieh",
        "Sumac",
        "Za'atar",
        "Herbes de Provence",
        "Italian Seasoning",
        "Poultry Seasoning",
        "Old Bay Seasoning",
        "Cajun Seasoning",
        "Creole Seasoning",
        "Taco Seasoning",
        "Fajita Seasoning",
        "Ranch Seasoning",
        "Celery Seed",
        "Sesame Seeds",
        "Poppy Seeds",
        "Nigella Seeds",
        "Hemp Seeds",
        "Flaxseeds",
        "Chia Seeds",
        "Curry powder",
        "Pumpkin Seeds",
        "Sunflower Seeds",
        "Fenugreek Seeds",
        "Mustard Seeds",
        "Caraway Seeds",
        "Fennel Seeds",
        "Anise Seeds",
        "Celery Seeds",
        "Cumin Seeds",
        "Coriander Seeds",
        "Dill Seeds",
        "Cardamom Pods",
        "Clove Buds",
        "Bay Berries",
        "Mace",
        "Szechuan Peppercorns",
        "Galangal",
        "Tamarind",
        "Amchoor",
        "Kala Namak",
        "Seafood Seasoning",
    ];

    const sugarsAndSweeteners = [
        "White Sugar",
        "Brown Sugar",
        "Raw Sugar",
        "Turbinado Sugar",
        "Muscovado Sugar",
        "Powdered Sugar",
        "Confectioners' Sugar",
        "Cane Sugar",
        "Beet Sugar",
        "Demerara Sugar",
        "Caster Sugar",
        "Palm Sugar",
        "Coconut Sugar",
        "Maple Sugar",
        "Maple Syrup",
        "Honey",
        "Agave Nectar",
        "Corn Syrup",
        "High Fructose Corn Syrup",
        "Molasses",
        "Blackstrap Molasses",
        "Golden Syrup",
        "Brown Rice Syrup",
        "Date Sugar",
        "Date Syrup",
        "Fruit Juice Concentrate",
        "Barley Malt Syrup",
        "Maltose",
        "Glucose",
        "Fructose",
        "Sucrose",
        "Lactose",
        "Stevia",
        "Erythritol",
        "Xylitol",
        "Sorbitol",
        "Mannitol",
        "Monk Fruit Sweetener",
        "Yacon Syrup",
        "Lucuma Powder",
        "Aspartame",
        "Sucralose",
        "Saccharin",
        "Acesulfame K",
        "Neotame",
        "Allulose",
        "Trehalose",
        "Isomalt",
        "Maltitol",
    ];

    const bakingIngredients = [
        "All-Purpose Flour",
        "Bread Flour",
        "Cake Flour",
        "Whole Wheat Flour",
        "Almond Flour",
        "Coconut Flour",
        "Pastry Flour",
        "Self-Rising Flour",
        "Cornmeal",
        "Cornstarch",
        "Baking Powder",
        "Baking Soda",
        "Yeast",
        "Salt",
        "Sugar",
        "Brown Sugar",
        "Powdered Sugar",
        "Raw Sugar",
        "Turbinado Sugar",
        "Muscovado Sugar",
        "Honey",
        "Maple Syrup",
        "Molasses",
        "Agave Nectar",
        "Corn Syrup",
        "Golden Syrup",
        "Brown Rice Syrup",
        "Milk",
        "Buttermilk",
        "Heavy Cream",
        "Half-and-Half",
        "Evaporated Milk",
        "Condensed Milk",
        "Butter",
        "Margarine",
        "Vegetable Oil",
        "Canola Oil",
        "Olive Oil",
        "Coconut Oil",
        "Shortening",
        "Lard",
        "Eggs",
        "Egg Whites",
        "Egg Yolks",
        "Vanilla Extract",
        "Almond Extract",
        "Lemon Extract",
        "Orange Extract",
        "Peppermint Extract",
        "Cocoa Powder",
        "Chocolate Chips",
        "Baking Chocolate",
        "White Chocolate",
        "Milk Chocolate",
        "Dark Chocolate",
        "Semi-Sweet Chocolate",
        "Unsweetened Chocolate",
        "Peanut Butter",
        "Nutella",
        "Nuts",
        "Almonds",
        "Walnuts",
        "Pecans",
        "Hazelnuts",
        "Macadamia Nuts",
        "Pistachios",
        "Cashews",
        "Raisins",
        "Dried Cranberries",
        "Dried Apricots",
        "Dried Cherries",
        "Dried Blueberries",
        "Dates",
        "Figs",
        "Coconut Flakes",
        "Oats",
        "Quick Oats",
        "Rolled Oats",
        "Steel-Cut Oats",
        "Cornflakes",
        "Rice Krispies",
        "Graham Crackers",
        "Breadcrumbs",
        "Gelatin",
        "Agar-Agar",
        "Pectin",
        "Cream of Tartar",
        "Butterscotch Chips",
        "Caramel",
        "Marshmallows",
        "Sprinkles",
        "Food Coloring",
        "Lemon Zest",
        "Orange Zest",
        "Cinnamon",
        "Nutmeg",
        "Cloves",
        "Ginger",
        "Allspice",
        "Cardamom",
        "Anise",
        "Pumpkin Pie Spice",
    ];

    const premadeDoughsAndWrappers = [
        "Puff Pastry",
        "Phyllo Dough",
        "Pizza Dough",
        "Pie Crust",
        "Croissant Dough",
        "Biscuit Dough",
        "Crescent Roll Dough",
        "Cookie Dough",
        "Bread Dough",
        "Tortilla",
        "Spring Roll Wrappers",
        "Egg Roll Wrappers",
        "Wonton Wrappers",
        "Dumpling Wrappers",
        "Gyoza Wrappers",
        "Tamale Wrappers",
        "Empanada Dough",
        "Challah Dough",
        "Sourdough",
        "Bagel Dough",
        "Pita Bread",
        "Naan Bread",
        "Lavash",
        "Focaccia Dough",
        "Brioche Dough",
        "Pretzel Dough",
        "Churro Dough",
        "Samosa Wrappers",
        "Bao Buns",
        "Corn Husks"
    ];

    const grainsAndCereals = [
        "Rice",
        "Brown Rice",
        "White Rice",
        "Basmati Rice",
        "Jasmine Rice",
        "Wild Rice",
        "Quinoa",
        "Barley",
        "Oats",
        "Millet",
        "Farro",
        "Bulgur",
        "Couscous",
        "Amaranth",
        "Teff",
        "Spelt",
        "Rye",
        "Sorghum",
        "Buckwheat",
        "Fonio",
        "Kamut",
        "Freekeh",
        "Triticale",
        "Wheat Berries",
        "Popcorn",
        "Cornmeal",
        "Grits",
        "Polenta",
        "Cracked Wheat",
        "Bran",
        "Rolled Oats",
        "Steel-Cut Oats",
        "Instant Oats",
        "Quick Oats",
        "Groats",
        "Quinoa Flakes",
        "Rice Flakes",
        "Wheat Flakes",
        "Corn Flakes",
        "Spelt Flakes",
        "Barley Flakes",
        "Rye Flakes",
        "Amaranth Flakes",
        "Buckwheat Flakes",
        "Teff Flakes",
        "Millet Flakes",
        "Chia Seeds",
        "Hemp Seeds",
        "Flaxseeds",
        "Pumpkin Seeds",
        "Sunflower Seeds",
        "Sesame Seeds",
        "Poppy Seeds",
        "Quinoa Seeds",
        "Barley Seeds",
        "Wheat Seeds",
        "Corn Seeds",
        "Rice Seeds",
        "Oat Seeds",
        "Spelt Seeds",
        "Rye Seeds",
        "Teff Seeds",
        "Millet Seeds",
        "Chia Seeds",
        "Hemp Seeds",
        "Flax Seeds",
        "Pumpkin Seeds",
        "Sunflower Seeds",
        "Sesame Seeds",
        "Poppy Seeds",
        "Buckwheat Groats",
        "Kasha",
        "Rice Krispies",
        "Granola",
        "Muesli",
        "Cheerios",
        "Cornflakes",
        "Wheat Bran",
        "Oat Bran",
        "Rice Bran",
        "All-Bran",
        "Special K",
        "Grape Nuts",
        "Raisin Bran",
        "Frosted Flakes",
        "Honey Nut Cheerios",
        "Lucky Charms",
        "Cocoa Puffs",
        "Trix",
        "Rice Chex",
        "Wheat Chex",
        "Corn Chex",
        "Rice Cakes",
        "Pop Tarts",
        "Cream of Wheat",
        "Farina",
        "Malt-O-Meal",
        "Grits",
        "Polenta"
    ];

    const legumes = [
        "Black Beans",
        "Navy Beans",
        "Pinto Beans",
        "Kidney Beans",
        "Lima Beans",
        "Great Northern Beans",
        "Cannellini Beans",
        "Garbanzo Beans",
        "Chickpeas",
        "Green Beans",
        "Soybeans",
        "Edamame",
        "Lentils",
        "Red Lentils",
        "Green Lentils",
        "Brown Lentils",
        "Yellow Lentils",
        "Split Peas",
        "Green Split Peas",
        "Yellow Split Peas",
        "Peanuts",
        "Black-Eyed Peas",
        "Fava Beans",
        "Broad Beans",
        "Mung Beans",
        "Adzuki Beans",
        "Bambara Beans",
        "Pigeon Peas",
        "Lupini Beans",
        "Marrowfat Peas",
        "Snow Peas",
        "Sugar Snap Peas",
        "Field Peas",
        "Crowder Peas",
        "Roman Beans",
        "Dragon Beans",
        "Flageolet Beans",
        "Tongues of Fire Beans",
        "Scarlet Runner Beans",
        "Christmas Lima Beans",
        "Cranberry Beans",
        "Rattlesnake Beans",
        "Appaloosa Beans",
        "Mayocoba Beans",
        "Tepary Beans",
        "Red Beans",
        "White Beans",
        "Pink Beans",
        "Yellow Beans",
        "Brown Beans",
        "Purple Beans",
        "Blue Beans",
        "Speckled Beans",
        "Tiger's Eye Beans",
        "Val Beans",
        "Rice Beans",
        "Cicerchia",
        "Guar Beans",
        "Winged Beans",
        "Hyacinth Beans",
        "Jack Beans",
        "Jicama Beans",
        "Moth Beans",
        "Rice Beans",
        "Tarwi"
    ];

    const pastas = [
        "Spaghetti",
        "Fettuccine",
        "Linguine",
        "Penne",
        "Rigatoni",
        "Macaroni",
        "Rotini",
        "Fusilli",
        "Orzo",
        "Farfalle",
        "Ziti",
        "Lasagna",
        "Ravioli",
        "Tortellini",
        "Gnocchi",
        "Cannelloni",
        "Manicotti",
        "Angel Hair",
        "Vermicelli",
        "Tagliatelle",
        "Pappardelle",
        "Bucatini",
        "Ditalini",
        "Conchiglie",
        "Cavatappi",
        "Gemelli",
        "Campanelle",
        "Orecchiette",
        "Mafaldine",
        "Paccheri",
        "Acini di Pepe",
        "Fregola",
        "Strozzapreti",
        "Bigoli",
        "Capellini",
        "Casarecce",
        "Cavatelli",
        "Chitarra",
        "Radiatori",
        "Sagnarelli",
        "Sagnette",
        "Scialatielli",
        "Trofie",
        "Busiate",
        "Ziti Candeloni",
        "Lorighittas",
        "Malloreddus",
        "Fideos",
        "Kluski",
        "Soba",
        "Udon"
    ];

    const breadsAndSaltySnacks = [
        "White Bread",
        "Whole Wheat Bread",
        "Sourdough",
        "Rye Bread",
        "Pumpernickel",
        "Baguette",
        "Ciabatta",
        "Focaccia",
        "Naan",
        "Pita Bread",
        "Tortilla",
        "Bagel",
        "English Muffin",
        "Croissant",
        "Brioche",
        "Challah",
        "Breadsticks",
        "Croutons",
        "Pretzel",
        "Soft Pretzel",
        "Crackers",
        "Ritz Crackers",
        "Saltine Crackers",
        "Graham Crackers",
        "Cheese Crackers",
        "Rice Crackers",
        "Pita Chips",
        "Tortilla Chips",
        "Potato Chips",
        "Corn Chips",
        "Popcorn",
        "Cheese Puffs",
        "Nachos",
        "Sun Chips",
        "Fritos",
        "Pretzel Chips",
        "Bagel Chips",
        "Crispbread",
        "Melba Toast",
        "Breadsticks",
        "Garlic Bread",
        "Cornbread",
        "Banana Bread",
        "Zucchini Bread",
        "Pumpkin Bread",
        "Pumpernickel Bread",
        "Soda Bread",
        "Flatbread",
        "Lavash",
        "Matzo",
        "Naan",
        "Papadum",
        "Chapati",
        "Roti",
        "Frybread"
    ];

    const oilsAndFats = [
        "Olive Oil",
        "Extra Virgin Olive Oil",
        "Vegetable Oil",
        "Canola Oil",
        "Sunflower Oil",
        "Peanut Oil",
        "Sesame Oil",
        "Coconut Oil",
        "Avocado Oil",
        "Grapeseed Oil",
        "Flaxseed Oil",
        "Hemp Oil",
        "Pumpkin Seed Oil",
        "Walnut Oil",
        "Almond Oil",
        "Hazelnut Oil",
        "Macadamia Oil",
        "Safflower Oil",
        "Soybean Oil",
        "Corn Oil",
        "Rice Bran Oil",
        "Palm Oil",
        "Butter",
        "Ghee",
        "Margarine",
        "Shortening",
        "Lard",
        "Duck Fat",
        "Chicken Fat",
        "Beef Tallow",
        "Bacon Fat",
        "Cocoa Butter",
        "Shea Butter",
        "Palm Kernel Oil",
        "Babassu Oil",
        "Argan Oil",
        "Moringa Oil",
        "Mustard Oil",
        "Neem Oil",
        "Kukui Nut Oil",
        "Perilla Oil",
        "Pistachio Oil",
        "Red Palm Oil",
        "Rice Bran Oil",
        "Emu Oil",
        "Fish Oil",
        "Krill Oil",
        "Cod Liver Oil",
        "Shark Liver Oil",
        "Camelina Oil",
        "Black Seed Oil",
        "Amaranth Oil",
        "Chia Seed Oil",
        "Linseed Oil",
        "Meadowfoam Oil",
        "Milk Thistle Oil",
        "Pequi Oil",
        "Poppyseed Oil",
        "Sea Buckthorn Oil",
        "Tomato Seed Oil",
        "Watermelon Seed Oil",
        "Wheat Germ Oil",
        "Apricot Kernel Oil",
        "Borage Oil",
        "Cherry Kernel Oil",
        "Cranberry Seed Oil",
        "Cucumber Seed Oil",
        "Elderberry Seed Oil",
        "Evening Primrose Oil"
    ];

    const dressingsAndVinegars = [
        "Ranch Dressing",
        "Caesar Dressing",
        "Blue Cheese Dressing",
        "Thousand Island Dressing",
        "French Dressing",
        "Italian Dressing",
        "Greek Dressing",
        "Balsamic Vinegar",
        "Red Wine Vinegar",
        "White Wine Vinegar",
        "Apple Cider Vinegar",
        "Rice Vinegar",
        "Malt Vinegar",
        "Sherry Vinegar",
        "Champagne Vinegar",
        "Distilled White Vinegar",
        "Black Vinegar",
        "Coconut Vinegar",
        "Raspberry Vinegar",
        "Tarragon Vinegar",
        "Herb Vinegar",
        "Garlic Vinegar",
        "Lemon Vinegar",
        "Lime Vinegar",
        "Ginger Vinegar",
        "Honey Vinegar",
        "Date Vinegar",
        "Pomegranate Vinegar",
        "Fig Vinegar",
        "Peach Vinegar",
        "Strawberry Vinegar",
        "Mango Vinegar",
        "Pear Vinegar",
        "Cranberry Vinegar",
        "Plum Vinegar",
        "Tomato Vinegar",
        "Bell Pepper Vinegar",
        "Chipotle Vinegar",
        "Jalapeño Vinegar",
        "Habanero Vinegar",
        "Smoked Vinegar",
        "Wasabi Vinegar",
        "Soy Sauce",
        "Tamari",
        "Teriyaki Sauce",
        "Ponzu Sauce",
        "Fish Sauce",
        "Oyster Sauce",
        "Hoisin Sauce",
        "Plum Sauce",
        "Duck Sauce",
        "Sweet and Sour Sauce",
        "Satay Sauce",
        "Peanut Sauce",
        "Chili Sauce",
        "Sriracha",
        "Hot Sauce",
        "BBQ Sauce",
        "Ketchup",
        "Mustard",
        "Mayonnaise",
        "Aioli",
        "Tahini",
        "Tapenade"
    ];

    const condiments = [
        "Ketchup",
        "Mustard",
        "Mayonnaise",
        "Relish",
        "Horseradish",
        "Hot Sauce",
        "BBQ Sauce",
        "Soy Sauce",
        "Worcestershire Sauce",
        "Teriyaki Sauce",
        "Fish Sauce",
        "Sriracha",
        "Chili Sauce",
        "Honey Mustard",
        "Dijon Mustard",
        "Yellow Mustard",
        "Spicy Brown Mustard",
        "Stone Ground Mustard",
        "Ranch Dressing",
        "Blue Cheese Dressing",
        "Caesar Dressing",
        "Italian Dressing",
        "Thousand Island Dressing",
        "French Dressing",
        "Greek Dressing",
        "Russian Dressing",
        "Balsamic Vinegar",
        "Red Wine Vinegar",
        "White Wine Vinegar",
        "Apple Cider Vinegar",
        "Rice Vinegar",
        "Malt Vinegar",
        "Sherry Vinegar",
        "Champagne Vinegar",
        "Distilled White Vinegar",
        "Black Vinegar",
        "Coconut Vinegar",
        "Raspberry Vinegar",
        "Tarragon Vinegar",
        "Herb Vinegar",
        "Garlic Vinegar",
        "Lemon Vinegar",
        "Lime Vinegar",
        "Ginger Vinegar",
        "Honey Vinegar",
        "Date Vinegar",
        "Pomegranate Vinegar",
        "Fig Vinegar",
        "Peach Vinegar",
        "Strawberry Vinegar",
        "Mango Vinegar",
        "Pear Vinegar",
        "Cranberry Vinegar",
        "Plum Vinegar",
        "Tomato Vinegar",
        "Bell Pepper Vinegar",
        "Chipotle Vinegar",
        "Jalapeño Vinegar",
        "Habanero Vinegar",
        "Smoked Vinegar",
        "Wasabi Vinegar",
        "Soy Sauce",
        "Tamari",
        "Ponzu Sauce",
        "Fish Sauce",
        "Oyster Sauce",
        "Hoisin Sauce",
        "Plum Sauce",
        "Duck Sauce",
        "Sweet and Sour Sauce",
        "Satay Sauce",
        "Peanut Sauce",
        "Chili Paste",
        "Curry Paste",
        "Miso Paste",
        "Tahini",
        "Tapenade",
        "Guacamole",
        "Salsa",
        "Pico de Gallo",
        "Chimichurri",
        "Pesto",
        "Tzatziki",
        "Harissa",
        "Romesco",
        "Aioli",
        "Remoulade",
        "Cocktail Sauce"
    ];

    const cannedFoods = [
        "Canned Tomatoes",
        "Canned Corn",
        "Canned Beans",
        "Canned Peas",
        "Canned Carrots",
        "Canned Green Beans",
        "Canned Mushrooms",
        "Canned Spinach",
        "Canned Beets",
        "Canned Artichokes",
        "Canned Asparagus",
        "Canned Potatoes",
        "Canned Pumpkin",
        "Canned Squash",
        "Canned Sweet Potatoes",
        "Canned Pineapple",
        "Canned Peaches",
        "Canned Pears",
        "Canned Apricots",
        "Canned Cherries",
        "Canned Fruit Cocktail",
        "Canned Applesauce",
        "Canned Mandarins",
        "Canned Grapefruit",
        "Canned Cranberries",
        "Canned Salsa",
        "Canned Jalapeños",
        "Canned Olives",
        "Canned Tuna",
        "Canned Salmon",
        "Canned Chicken",
        "Canned Beef",
        "Canned Ham",
        "Canned Spam",
        "Canned Sardines",
        "Canned Anchovies",
        "Canned Clams",
        "Canned Crab",
        "Canned Shrimp",
        "Canned Oysters",
        "Canned Soup",
        "Canned Chili",
        "Canned Stew",
        "Canned Ravioli",
        "Canned Spaghetti",
        "Canned Macaroni",
        "Canned Beans and Franks",
        "Canned Tamales",
        "Canned Enchiladas",
        "Canned Refried Beans",
        "Canned Black Beans",
        "Canned Kidney Beans",
        "Canned Garbanzo Beans",
        "Canned White Beans",
        "Canned Lentils",
        "Canned Mixed Vegetables",
        "Canned Pimientos",
        "Canned Green Chiles",
        "Canned Chipotle Peppers",
        "Canned Hominy",
        "Canned Sauerkraut",
        "Canned Kimchi",
        "Canned Water Chestnuts",
        "Canned Bamboo Shoots",
        "Canned Coconut Milk",
        "Canned Evaporated Milk",
        "Canned Condensed Milk",
        "Canned Soup Base",
        "Canned Bouillon",
        "Canned Gravy",
        "Canned Tomato Paste",
        "Canned Tomato Sauce",
        "Canned Salsa Verde",
        "Canned Tomatillos",
        "Canned Pasta Sauce",
        "Canned Alfredo Sauce",
        "Canned Pesto Sauce",
        "Canned Marinara Sauce",
        "Canned Bolognese Sauce",
        "Canned Cheese Sauce",
        "Canned Mustard",
        "Canned Ketchup",
        "Canned Mayo",
        "Canned BBQ Sauce",
        "Canned Soy Sauce",
        "Canned Hot Sauce",
        "Canned Relish",
        "Canned Horseradish",
        "Canned Tartar Sauce",
        "Canned Peanut Butter",
        "Canned Jam",
        "Canned Jelly",
        "Canned Marmalade"
    ];

    const saucesSpreadsAndDips = [
        "Ketchup",
        "Mustard",
        "Mayonnaise",
        "BBQ Sauce",
        "Soy Sauce",
        "Teriyaki Sauce",
        "Hot Sauce",
        "Sriracha",
        "Hoisin Sauce",
        "Fish Sauce",
        "Oyster Sauce",
        "Worcestershire Sauce",
        "Tartar Sauce",
        "Cocktail Sauce",
        "Chili Sauce",
        "Sweet and Sour Sauce",
        "Duck Sauce",
        "Plum Sauce",
        "Tahini",
        "Hummus",
        "Guacamole",
        "Salsa",
        "Pico de Gallo",
        "Ranch Dip",
        "French Onion Dip",
        "Spinach Dip",
        "Artichoke Dip",
        "Buffalo Chicken Dip",
        "Cheese Dip",
        "Queso",
        "Nacho Cheese Sauce",
        "Pesto",
        "Marinara Sauce",
        "Alfredo Sauce",
        "Pasta Sauce",
        "Pizza Sauce",
        "Bolognese Sauce",
        "Puttanesca Sauce",
        "Arrabbiata Sauce",
        "Vodka Sauce",
        "Carbonara Sauce",
        "Hollandaise Sauce",
        "Béarnaise Sauce",
        "Bechamel Sauce",
        "Mornay Sauce",
        "Velouté Sauce",
        "Gravy",
        "Brown Sauce",
        "Red Sauce",
        "Tomato Sauce",
        "Apple Sauce",
        "Cranberry Sauce",
        "Mango Chutney",
        "Tamarind Chutney",
        "Green Chutney",
        "Tomato Chutney",
        "Onion Chutney",
        "Garlic Chutney",
        "Curry Sauce",
        "Korma Sauce",
        "Tikka Masala Sauce",
        "Vindaloo Sauce",
        "Mango Salsa",
        "Pineapple Salsa",
        "Corn Salsa",
        "Black Bean Salsa",
        "Tomatillo Salsa",
        "Avocado Salsa",
        "Yogurt Sauce",
        "Cilantro Sauce",
        "Mint Sauce",
        "Chimichurri",
        "Harissa",
        "Romesco",
        "Aioli",
        "Remoulade",
        "Blue Cheese Sauce",
        "Buffalo Sauce",
        "Gochujang",
        "Miso",
        "Ponzu",
        "Dijon Mustard",
        "Honey Mustard",
        "Whole Grain Mustard",
        "Spicy Brown Mustard",
        "English Mustard",
        "German Mustard",
        "Chinese Mustard",
        "French Mustard",
        "Russian Dressing",
        "Italian Dressing",
        "Greek Dressing",
        "Caesar Dressing",
        "Ranch Dressing",
        "Blue Cheese Dressing",
        "Thousand Island Dressing",
        "Balsamic Vinaigrette",
        "Red Wine Vinaigrette",
        "White Wine Vinaigrette",
        "Apple Cider Vinaigrette",
        "Honey Mustard Dressing",
        "Asian Sesame Dressing",
        "Ginger Dressing",
        "Miso Dressing",
        "Tahini Dressing"
    ];

    const soupsStewsAndBroths = [
        "Chicken Soup",
        "Beef Soup",
        "Vegetable Soup",
        "Tomato Soup",
        "Mushroom Soup",
        "Lentil Soup",
        "Split Pea Soup",
        "Minestrone",
        "Clam Chowder",
        "Corn Chowder",
        "Potato Soup",
        "Broccoli Cheddar Soup",
        "French Onion Soup",
        "Chicken Noodle Soup",
        "Beef Noodle Soup",
        "Chicken Tortilla Soup",
        "Tom Yum Soup",
        "Tom Kha Soup",
        "Hot and Sour Soup",
        "Miso Soup",
        "Wonton Soup",
        "Egg Drop Soup",
        "Pho",
        "Ramen",
        "Udon Soup",
        "Soba Soup",
        "Matzo Ball Soup",
        "Borscht",
        "Gazpacho",
        "Vichyssoise",
        "Fish Chowder",
        "Seafood Bisque",
        "Lobster Bisque",
        "Crab Bisque",
        "Shrimp Bisque",
        "Oyster Stew",
        "Gumbo",
        "Jambalaya",
        "Chicken Stew",
        "Beef Stew",
        "Lamb Stew",
        "Pork Stew",
        "Vegetable Stew",
        "Irish Stew",
        "Brunswick Stew",
        "Brisket Stew",
        "Chili",
        "Turkey Chili",
        "Vegetarian Chili",
        "White Chicken Chili"
    ];

    const desserts = [
        "Chocolate Cake",
        "Vanilla Cake",
        "Red Velvet Cake",
        "Carrot Cake",
        "Cheesecake",
        "Brownies",
        "Blondies",
        "Chocolate Chip Cookies",
        "Sugar Cookies",
        "Snickerdoodles",
        "Peanut Butter Cookies",
        "Oatmeal Raisin Cookies",
        "Macarons",
        "Macaroons",
        "Biscotti",
        "Shortbread",
        "Gingerbread",
        "Pound Cake",
        "Angel Food Cake",
        "Devil's Food Cake",
        "Fruit Cake",
        "Bundt Cake",
        "Cupcakes",
        "Muffins",
        "Scones",
        "Doughnuts",
        "Cinnamon Rolls",
        "Croissants",
        "Eclairs",
        "Cream Puffs",
        "Tiramisu",
        "Panna Cotta",
        "Creme Brulee",
        "Flan",
        "Custard",
        "Pudding",
        "Rice Pudding",
        "Bread Pudding",
        "Churros",
        "Cannoli",
        "Baklava",
        "Tart",
        "Pie",
        "Apple Pie",
        "Pumpkin Pie",
        "Pecan Pie",
        "Cherry Pie",
        "Blueberry Pie",
        "Raspberry Pie",
        "Blackberry Pie",
        "Lemon Meringue Pie",
        "Key Lime Pie",
        "Coconut Cream Pie",
        "Banana Cream Pie",
        "Chocolate Pie",
        "Peach Cobbler",
        "Apple Crisp",
        "Fruit Crumble",
        "Trifle",
        "Ice Cream",
        "Gelato",
        "Sorbet",
        "Sherbet",
        "Fudge",
        "Marshmallows",
        "Divinity",
        "Taffy",
        "Caramel",
        "Toffee",
        "Britannia",
        "Nougat",
        "Halva",
        "Jelly Beans",
        "Gummy Bears",
        "Gummy Worms",
        "Chocolate Bars",
        "Chocolate Truffles",
        "Chocolate Covered Strawberries",
        "Fruit Salad",
        "Ambrosia",
        "Baked Alaska",
        "Bananas Foster",
        "Crepes",
        "Waffles",
        "Pancakes",
        "French Toast",
        "Bread and Butter Pudding",
        "Tres Leches Cake",
        "Sopapillas",
        "Buñuelos"
    ];

    const wineBeerAndSpirits = [
        "Red Wine",
        "White Wine",
        "Rose Wine",
        "Sparkling Wine",
        "Champagne",
        "Prosecco",
        "Cava",
        "Port",
        "Sherry",
        "Madeira",
        "Vermouth",
        "Beer",
        "Ale",
        "Lager",
        "Stout",
        "Porter",
        "Pilsner",
        "Pale Ale",
        "India Pale Ale (IPA)",
        "Wheat Beer",
        "Saison",
        "Sour Beer",
        "Barleywine",
        "Bitter",
        "Brown Ale",
        "Amber Ale",
        "Blonde Ale",
        "Red Ale",
        "Scotch Ale",
        "Belgian Ale",
        "Bock",
        "Doppelbock",
        "Eisbock",
        "Tripel",
        "Quadruple",
        "Saison",
        "Gose",
        "Lambic",
        "Fruit Beer",
        "Hard Cider",
        "Mead",
        "Sake",
        "Whiskey",
        "Bourbon",
        "Scotch",
        "Rye Whiskey",
        "Irish Whiskey",
        "Canadian Whiskey",
        "Japanese Whiskey"
    ];

    const beverages = [
        "Water",
        "Sparkling Water",
        "Mineral Water",
        "Tonic Water",
        "Club Soda",
        "Cola",
        "Diet Cola",
        "Lemon-Lime Soda",
        "Root Beer",
        "Ginger Ale",
        "Ginger Beer",
        "Orange Soda",
        "Grape Soda",
        "Cream Soda",
        "Fruit Punch",
        "Lemonade",
        "Iced Tea",
        "Sweet Tea",
        "Green Tea",
        "Black Tea",
        "Herbal Tea",
        "Chamomile Tea",
        "Peppermint Tea",
        "Rooibos Tea",
        "Earl Grey Tea",
        "Chai Tea",
        "Matcha",
        "Coffee",
        "Espresso",
        "Cappuccino",
        "Latte",
        "Mocha",
        "Macchiato",
        "Hot Chocolate",
        "Cocoa",
        "Milk",
        "Skim Milk",
        "Whole Milk",
        "2% Milk",
        "Soy Milk",
        "Almond Milk",
        "Coconut Milk",
        "Oat Milk",
        "Rice Milk",
        "Hemp Milk",
        "Buttermilk",
        "Eggnog",
        "Orange Juice",
        "Apple Juice",
        "Grape Juice",
        "Cranberry Juice",
        "Pineapple Juice",
        "Tomato Juice",
        "Carrot Juice",
        "Vegetable Juice",
        "Beet Juice",
        "Pomegranate Juice",
        "Mango Juice",
        "Peach Juice",
        "Papaya Juice",
        "Strawberry Juice",
        "Lemon Juice",
        "Lime Juice",
        "Grapefruit Juice",
        "Watermelon Juice",
        "Cucumber Juice",
        "Coconut Water",
        "Smoothie",
        "Protein Shake",
        "Milkshake",
        "Kombucha",
        "Kvass",
        "Horchata",
        "Atole",
        "Chicha"
    ];

    const supplements = [
        "Multivitamins",
        "Vitamin A",
        "Vitamin B Complex",
        "Vitamin B1 (Thiamine)",
        "Vitamin B2 (Riboflavin)",
        "Vitamin B3 (Niacin)",
        "Vitamin B5 (Pantothenic Acid)",
        "Vitamin B6 (Pyridoxine)",
        "Vitamin B7 (Biotin)",
        "Vitamin B9 (Folic Acid)",
        "Vitamin B12 (Cobalamin)",
        "Vitamin C",
        "Vitamin D",
        "Vitamin E",
        "Vitamin K",
        "Calcium",
        "Magnesium",
        "Iron",
        "Zinc",
        "Copper",
        "Manganese",
        "Selenium",
        "Chromium",
        "Iodine",
        "Potassium",
        "Omega-3 Fatty Acids",
        "Fish Oil",
        "Flaxseed Oil",
        "Chia Seed Oil",
        "Hemp Seed Oil",
        "Borage Oil",
        "Evening Primrose Oil",
        "Probiotics",
        "Prebiotics",
        "Fiber",
        "Protein Powder",
        "Whey Protein",
        "Casein Protein",
        "Soy Protein",
        "Pea Protein",
        "Hemp Protein",
        "Brown Rice Protein",
        "Collagen",
        "Creatine",
        "Glutamine",
        "Branched-Chain Amino Acids (BCAAs)",
        "L-Carnitine",
        "Coenzyme Q10 (CoQ10)",
        "Alpha-Lipoic Acid",
        "Resveratrol",
        "Curcumin",
        "Turmeric",
        "Ginger",
        "Garlic",
        "Green Tea Extract",
        "Echinacea",
        "Elderberry",
        "Ashwagandha",
        "Rhodiola",
        "Ginseng",
        "Maca",
        "Cordyceps",
        "Reishi",
        "Chaga",
        "Lion's Mane",
        "Astragalus",
        "Milk Thistle",
        "Saw Palmetto",
        "St. John's Wort",
        "Valerian Root",
        "Melatonin",
        "5-HTP",
        "SAMe"
    ];


    const householdItems = [
        "Air fryer",
        "Blender",
        "Bread maker",
        "Bread slicer",
        "Butter churn",
        "Candy thermometer",
        "Cast iron skillet",
        "Cheese grater",
        "Coffee grinder",
        "Coffee maker",
        "Crepe maker",
        "Deep fryer",
        "Electric can opener",
        "Electric kettle",
        "Fondue pot",
        "Food processor",
        "Food steamer",
        "Grill",
        "Handheld mixer",
        "Hot pot",
        "Ice cream maker",
        "Immersion blender",
        "Induction cooktop",
        "Juicer",
        "Mandoline",
        "Meat grinder",
        "Meat slicer",
        "Milk frother",
        "Microwave",
        "Non-stick pan",
        "Oven",
        "Panini press",
        "Pasta maker",
        "Peeler",
        "Pizza oven",
        "Pizza stone",
        "Popcorn maker",
        "Potato masher",
        "Pressure cooker",
        "Rice cooker",
        "Salad spinner",
        "Sandwich maker",
        "Sauce pan",
        "Sausage stuffer",
        "Slow cooker",
        "Smoker",
        "Snow cone machine",
        "Sous vide",
        "Spice grinder",
        "Spiralizer",
        "Stand mixer",
        "Stockpot",
        "Stovetop",
        "Toaster",
        "Toaster oven",
        "Vacuum sealer",
        "Waffle maker",
        "Yogurt maker",
        "Zester"
    ];


    const sections = {
        pantryEssentials: pantryEssentials,
        vegetablesAndGreens: vegetablesAndGreens,
        mushrooms: mushrooms,
        fruits: fruits,
        nutsAndSeeds: nutsAndSeeds,
        cheeses: cheeses,
        meatAndDairySubstitutes: meatAndDairySubstitutes,
        seafood: seafood,
        herbsAndSpices: herbsAndSpices,
        sugarsAndSweeteners: sugarsAndSweeteners,
        bakingIngredients: bakingIngredients,
        premadeDoughsAndWrappers: premadeDoughsAndWrappers,
        grainsAndCereals: grainsAndCereals,
        legumes: legumes,
        pastas: pastas,
        breadsAndSaltySnacks: breadsAndSaltySnacks,
        oilsAndFats: oilsAndFats,
        dressingsAndVinegars: dressingsAndVinegars,
        condiments: condiments,
        cannedFoods: cannedFoods,
        saucesSpreadsAndDips: saucesSpreadsAndDips,
        soupsStewsAndBroths: soupsStewsAndBroths,
        desserts: desserts,
        wineBeerAndSpirits: wineBeerAndSpirits,
        beverages: beverages,
        supplements: supplements
    };

    const toggleExpandedSection = (section) => {
        setExpandedSection(expandedSection === section ? null : section);
    };

    const addUserPreference = (preference) => {
        if (!userPreferences.includes(preference)) {
            dispatch({ type: 'ADD_USER_PREFERENCE', payload: { preference, currentPreferences: userPreferences } });
        }
    };

    const removeUserPreference = (preference) => {
        dispatch({ type: 'REMOVE_USER_PREFERENCE', payload: { preference, currentPreferences: userPreferences } });
    };

    const addUserHouseholdItem = (item) => {
        if (!userHouseholdItems.includes(item)) {
            dispatch({ type: 'ADD_USER_HOUSEHOLD_ITEM', payload: { item, currentHouseholdItems: userHouseholdItems } });
        }
    };

    const removeUserHouseholdItem = (item) => {
        dispatch({ type: 'REMOVE_USER_HOUSEHOLD_ITEM', payload: { item, currentHouseholdItems: userHouseholdItems } });
    };

    useEffect(() => {
        dispatch({ type: 'FETCH_USER_PREFERENCES' });
        dispatch({ type: 'FETCH_USER_HOUSEHOLD_ITEMS' });
        setPreferencesToDisplay(pantryEssentials);
        setHouseholdItemsToDisplay(householdItems);
    }, [dispatch]);

    const theme = useTheme();
    const primaryColor = '#df321b';
    const secondaryColor = '#4A4A4A';
    const tertiaryColor = '#A84430';  // Slightly lighter shade of primary color

    const buttonStyle = {
        margin: theme.spacing(1),
        borderRadius: '20px',
        padding: theme.spacing(1, 2),
        fontSize: '0.875rem',
        textTransform: 'none',
        boxShadow: theme.shadows[2],
        transition: theme.transitions.create(['background-color', 'transform'], {
            duration: theme.transitions.duration.short,
        }),
        border: `2px solid ${tertiaryColor}`,
        backgroundColor: theme.palette.common.white,
        color: tertiaryColor,
        '&:hover': {
            backgroundColor: secondaryColor,
            color: theme.palette.common.white,
        },
    };

    const selectedButtonStyle = {
        ...buttonStyle,
        backgroundColor: primaryColor,
        color: theme.palette.common.white,
        border: `2px solid ${primaryColor}`,
    };

    const isXsScreen = useMediaQuery(theme.breakpoints.down('xs'));
    const isSmScreen = useMediaQuery(theme.breakpoints.down('sm'));

    return (
        <div>
            <Header />
            <div style={{
                padding: theme.spacing(2), maxWidth: '1200px', margin: '0 auto',
                paddingTop: isXsScreen || isSmScreen ? '50px' : '0px',
            }}>
                {Object.keys(sections).map((section, idx) => (
                    <div key={idx}>
                        <Accordion expanded={expandedSection === section} onChange={() => toggleExpandedSection(section)}>
                            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                                <Typography style={{ fontSize: '1.2rem', fontWeight: 'bold' }}>
                                    {section.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())}
                                </Typography>
                            </AccordionSummary>
                            <AccordionDetails>
                                <div style={{ display: 'flex', flexWrap: 'wrap', gap: theme.spacing(1) }}>
                                    {sections[section].slice(15).map((item, index) => {
                                        const isSelected = userPreferences.includes(item);
                                        return (
                                            <Button
                                                key={index}
                                                variant="contained"
                                                style={isSelected ? selectedButtonStyle : buttonStyle}
                                                onClick={() => isSelected ? removeUserPreference(item) : addUserPreference(item)}
                                                onMouseEnter={(e) => {
                                                    e.currentTarget.style.transform = 'scale(1.08)';
                                                    e.currentTarget.style.boxShadow = theme.shadows[4];
                                                }}
                                                onMouseLeave={(e) => {
                                                    e.currentTarget.style.transform = isSelected ? 'scale(1.05)' : 'scale(1)';
                                                    e.currentTarget.style.boxShadow = theme.shadows[2];
                                                }}
                                            >
                                                {item}
                                            </Button>
                                        );
                                    })}
                                </div>
                            </AccordionDetails>
                        </Accordion>
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: theme.spacing(1), marginTop: theme.spacing(1) }}>
                            {sections[section].slice(0, 15).map((item, index) => {
                                const isSelected = userPreferences.includes(item);
                                return (
                                    <Button
                                        key={index}
                                        variant="contained"
                                        style={isSelected ? selectedButtonStyle : buttonStyle}
                                        onClick={() => isSelected ? removeUserPreference(item) : addUserPreference(item)}
                                        onMouseEnter={(e) => {
                                            e.currentTarget.style.transform = 'scale(1.08)';
                                            e.currentTarget.style.boxShadow = theme.shadows[4];
                                        }}
                                        onMouseLeave={(e) => {
                                            e.currentTarget.style.transform = isSelected ? 'scale(1.05)' : 'scale(1)';
                                            e.currentTarget.style.boxShadow = theme.shadows[2];
                                        }}
                                    >
                                        {item}
                                    </Button>
                                );
                            })}
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );

}

export default Pantry;